; Zadarma Wholesale DID Provider
; Server: sip.zadarma.com
; Login: 517132

[zadarma-transport]
type=transport
protocol=udp
bind=0.0.0.0:5090
external_media_address=3.11.229.68
external_signaling_address=3.11.229.68
local_net=172.26.0.0/16
local_net=127.0.0.0/8

[zadarma-registration]
type=registration
transport=zadarma-transport
outbound_auth=zadarma-auth
server_uri=sip:sip.zadarma.com
client_uri=sip:517132@sip.zadarma.com
retry_interval=60
expiration=600
line=yes
endpoint=zadarma-endpoint

[zadarma-auth]
type=auth
auth_type=userpass
username=517132
password=Lr85j2dxDg

[zadarma-aor]
type=aor
contact=sip:sip.zadarma.com
qualify_frequency=60

[zadarma-endpoint]
type=endpoint
transport=zadarma-transport
context=from-zadarma
disallow=all
allow=alaw
allow=ulaw
outbound_auth=zadarma-auth
aors=zadarma-aor
from_user=517132
from_domain=sip.zadarma.com
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[zadarma-identify]
type=identify
endpoint=zadarma-endpoint
match=sip.zadarma.com
