; Zadarma Wholesale DID Provider
; Server: sip.zadarma.com (185.45.152.180)
; Login: 517132

[zadarma-registration]
type=registration
outbound_auth=zadarma-auth
server_uri=sip:sip.zadarma.com
client_uri=sip:517132@sip.zadarma.com
retry_interval=60
expiration=600
line=yes
endpoint=zadarma-endpoint
contact_user=517132

[zadarma-auth]
type=auth
auth_type=userpass
username=517132
password=Lr85j2dxDg

[zadarma-aor]
type=aor
contact=sip:sip.zadarma.com
qualify_frequency=60

[zadarma-endpoint]
type=endpoint
context=from-zadarma
disallow=all
allow=alaw
allow=ulaw
outbound_auth=zadarma-auth
aors=zadarma-aor
from_user=517132
from_domain=sip.zadarma.com
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[zadarma-identify]
type=identify
endpoint=zadarma-endpoint
match=185.45.152.180
