server {
    server_name search.hardinai.co.uk;
    location / {
        proxy_pass http://localhost:5008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    listen 80;
}
