server {
    listen 80;
    server_name hardinai.co.uk www.hardinai.co.uk;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hardinai.co.uk www.hardinai.co.uk;

    ssl_certificate /etc/letsencrypt/live/hardinai.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hardinai.co.uk/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /home/ubuntu/hardinai.co.uk;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    if ($host = ai.hardinai.co.uk) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name ai.hardinai.co.uk;
    return 301 https://ai.hardinai.co.uk$request_uri;
}

server {
    listen 443 ssl;
    server_name ai.hardinai.co.uk;
    ssl_certificate /etc/letsencrypt/live/ai.hardinai.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ai.hardinai.co.uk/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300;
    }
}
